import type { LayerSpecification } from 'maplibre-gl';
import {
  BACKGROUND_COLOR,
  LANDUSE_COLORS,
  ROAD_COLORS,
  ROAD_WIDTHS,
  BUILDING_COLORS,
} from './constants';

export const createMapLayers = (): LayerSpecification[] => [
  {
    id: 'background',
    type: 'background',
    paint: {
      'background-color': BACKGROUND_COLOR,
    },
  },
  {
    id: 'landuse-fill',
    type: 'fill',
    source: 'landuse',
    'source-layer': 'landuse',
    paint: {
      'fill-color': [
        'match',
        ['get', 'class'],
        'forest',
        LANDUSE_COLORS.forest,
        'grass',
        LANDUSE_COLORS.grass,
        'park',
        LANDUSE_COLORS.park,
        'water',
        LANDUSE_COLORS.water,
        'residential',
        LANDUSE_COLORS.residential,
        'commercial',
        LANDUSE_COLORS.commercial,
        'industrial',
        LANDUSE_COLORS.industrial,
        LANDUSE_COLORS.default,
      ],
      'fill-opacity': 0.8,
    },
  },
  {
    id: 'roads-line',
    type: 'line',
    source: 'roads',
    'source-layer': 'roads',
    paint: {
      'line-color': [
        'match',
        ['get', 'road_class'],
        'motorway',
        ROAD_COLORS.motorway,
        'trunk',
        ROAD_COLORS.trunk,
        'primary',
        ROAD_COLORS.primary,
        'secondary',
        ROAD_COLORS.secondary,
        'tertiary',
        ROAD_COLORS.tertiary,
        ROAD_COLORS.default,
      ],
      'line-width': [
        'match',
        ['get', 'road_class'],
        'motorway',
        ROAD_WIDTHS.motorway,
        'trunk',
        ROAD_WIDTHS.trunk,
        'primary',
        ROAD_WIDTHS.primary,
        'secondary',
        ROAD_WIDTHS.secondary,
        'tertiary',
        ROAD_WIDTHS.tertiary,
        ROAD_WIDTHS.default,
      ],
      'line-opacity': 0.9,
    },
  },
  {
    id: 'buildings-fill',
    type: 'fill',
    source: 'buildings',
    'source-layer': 'buildings',
    paint: {
      'fill-color': BUILDING_COLORS.fill,
      'fill-opacity': 0.9,
    },
  },
  {
    id: 'buildings-3d',
    type: 'fill-extrusion',
    source: 'buildings',
    'source-layer': 'buildings',
    paint: {
      'fill-extrusion-color': BUILDING_COLORS.extrusion,
      'fill-extrusion-height': [
        'case',
        ['>', ['get', 'height'], 0],
        ['get', 'height'],
        ['has', 'num_floors'],
        ['*', ['get', 'num_floors'], 3.5],
        8,
      ],
      'fill-extrusion-base': 0,
      'fill-extrusion-opacity': 0.95,
    },
  },
];

/*TODO modify this to good default*/
