import { ROAD_COLORS, ROAD_WIDTHS, LANDUSE_COLORS } from './constants';
import type { ExpressionSpecification } from 'maplibre-gl';

export const ROAD_STYLE_CONFIGS = {
  default: {
    color: [
      'match',
      ['get', 'road_class'],
      'motorway',
      ROAD_COLORS.motorway,
      'trunk',
      ROAD_COLORS.trunk,
      'primary',
      ROAD_COLORS.primary,
      'secondary',
      ROAD_COLORS.secondary,
      'tertiary',
      ROAD_COLORS.tertiary,
      ROAD_COLORS.default,
    ] as ExpressionSpecification,
    width: [
      'match',
      ['get', 'road_class'],
      'motorway',
      ROAD_WIDTHS.motorway,
      'trunk',
      ROAD_WIDTHS.trunk,
      'primary',
      ROAD_WIDTHS.primary,
      'secondary',
      ROAD_WIDTHS.secondary,
      'tertiary',
      ROAD_WIDTHS.tertiary,
      ROAD_WIDTHS.default,
    ] as ExpressionSpecification,
  },
  minimal: {
    color: '#606070',
    width: [
      'match',
      ['get', 'road_class'],
      'motorway',
      2,
      'trunk',
      1.5,
      'primary',
      1.2,
      'secondary',
      1,
      'tertiary',
      0.8,
      0.5,
    ] as ExpressionSpecification,
  },
  prominent: {
    color: [
      'match',
      ['get', 'road_class'],
      'motorway',
      '#ff6b4a',
      'trunk',
      '#ff8c69',
      'primary',
      '#ffa07a',
      'secondary',
      '#ffd4a3',
      'tertiary',
      '#ffe5c2',
      '#e0e0f0',
    ] as ExpressionSpecification,
    width: [
      'match',
      ['get', 'road_class'],
      'motorway',
      8,
      'trunk',
      7,
      'primary',
      6,
      'secondary',
      4.5,
      'tertiary',
      3,
      2,
    ] as ExpressionSpecification,
  },
};

export const LANDUSE_STYLE_CONFIGS = {
  vibrant: {
    opacity: 0.8,
    color: [
      'match',
      ['get', 'class'],
      'forest',
      LANDUSE_COLORS.forest,
      'grass',
      LANDUSE_COLORS.grass,
      'park',
      LANDUSE_COLORS.park,
      'water',
      LANDUSE_COLORS.water,
      'residential',
      LANDUSE_COLORS.residential,
      'commercial',
      LANDUSE_COLORS.commercial,
      'industrial',
      LANDUSE_COLORS.industrial,
      LANDUSE_COLORS.default,
    ] as ExpressionSpecification,
  },
  subtle: {
    opacity: 0.3,
    color: [
      'match',
      ['get', 'class'],
      'forest',
      '#3a3a4a',
      'grass',
      '#353545',
      'park',
      '#383848',
      'water',
      '#2a3a4a',
      'residential',
      '#303035',
      'commercial',
      '#353540',
      'industrial',
      '#3a3a45',
      '#303038',
    ] as ExpressionSpecification,
  },
  monochrome: {
    opacity: 0.5,
    color: [
      'match',
      ['get', 'class'],
      'forest',
      '#404050',
      'grass',
      '#454555',
      'park',
      '#484858',
      'water',
      '#303040',
      'residential',
      '#383840',
      'commercial',
      '#3d3d45',
      'industrial',
      '#424248',
      '#383840',
    ] as ExpressionSpecification,
  },
};
